# Introducción a Pandas DataFrames

Pandas es una biblioteca de Python de código abierto que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento y fáciles de usar. La estructura de datos principal de Pandas es el **DataFrame**.

Un **DataFrame** es una estructura de datos tabular bidimensional, con etiquetas de columnas y etiquetas de filas (índices). Es similar a una hoja de cálculo, una tabla SQL o un diccionario de objetos Series. Es la estructura de datos más utilizada en Pandas y es muy versátil para manipular y analizar datos.

### Características clave de un DataFrame:
*   **Etiquetado de ejes**: Tanto las filas como las columnas tienen etiquetas (índices). Esto facilita la selección y manipulación de datos.
*   **Heterogéneo**: Puede contener columnas de diferentes tipos de datos (entero, flotante, cadena, booleano, etc.).
*   **Tamaño mutable**: Puede añadir o eliminar columnas y filas.
*   **Alineación automática de datos**: Durante las operaciones, Pandas alinea los datos automáticamente basándose en las etiquetas de los índices, lo que ayuda a prevenir errores y a realizar operaciones complejas de forma sencilla.

In [ ]:
import pandas as pd
import numpy as np

print("Pandas importado exitosamente.")

Pandas importado exitosamente.

## 1. Creación de DataFrames

Hay varias maneras de crear un DataFrame. Aquí exploraremos las más comunes:

### a) Desde un diccionario de listas o Series

In [ ]:
# Crear un DataFrame a partir de un diccionario de listas
data = {
    'Nombre': ['Alice', 'Bob', 'Charlie', 'David'],
    'Edad': [25, 30, 35, 40],
    'Ciudad': ['Nueva York', 'Londres', 'París', 'Tokio']
}
df_dict = pd.DataFrame(data)
print("DataFrame creado desde diccionario de listas:")
display(df_dict)

DataFrame creado desde diccionario de listas:

    Nombre  Edad      Ciudad
0    Alice    25  Nueva York
1      Bob    30     Londres
2  Charlie    35       París
3    David    40       Tokio

### b) Desde una lista de diccionarios

In [ ]:
# Crear un DataFrame a partir de una lista de diccionarios
data_list_dict = [
    {'Nombre': 'Eve', 'Edad': 28, 'Ciudad': 'Berlín'},
    {'Nombre': 'Frank', 'Edad': 32, 'Ciudad': 'Roma'},
    {'Nombre': 'Grace', 'Edad': 22, 'Ciudad': 'Madrid'}
]
df_list_dict = pd.DataFrame(data_list_dict)
print("DataFrame creado desde lista de diccionarios:")
display(df_list_dict)

### c) Desde un array NumPy

In [ ]:
# Crear un DataFrame a partir de un array NumPy
np_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
df_numpy = pd.DataFrame(np_array, columns=['Col A', 'Col B', 'Col C'], index=['Fila 1', 'Fila 2', 'Fila 3'])
print("DataFrame creado desde array NumPy:")
display(df_numpy)

### d) Desde un archivo CSV (el método más común)

In [ ]:
# Para demostrar la carga de CSV, crearemos un archivo CSV de ejemplo primero
csv_data = """ID,Producto,Precio,Cantidad
1,Manzana,1.5,100
2,Plátano,0.75,150
3,Naranja,1.2,80
4,Uva,2.0,50
"""

with open('productos.csv', 'w') as f:
    f.write(csv_data)

# Cargar el DataFrame desde un archivo CSV
df_csv = pd.read_csv('productos.csv')
print("DataFrame creado desde archivo CSV (productos.csv):")
display(df_csv)

## 2. Exploración Básica del DataFrame

Una vez que tenemos un DataFrame, es fundamental entender su estructura y contenido. Aquí están algunas de las funciones más útiles para una exploración inicial.

In [ ]:
# Usaremos df_dict para esta sección, o df_csv si lo prefieres.
df = df_dict.copy() # Hacemos una copia para no modificar el original

print("DataFrame actual:")
display(df)

# .head() - Muestra las primeras N filas (por defecto 5)
print("\nPrimeras 2 filas con .head(2):")
display(df.head(2))

# .tail() - Muestra las últimas N filas (por defecto 5)
print("\nÚltima fila con .tail(1):")
display(df.tail(1))

# .info() - Proporciona un resumen conciso del DataFrame
print("\nInformación del DataFrame con .info():")
df.info()

# .describe() - Genera estadísticas descriptivas de las columnas numéricas
print("\nEstadísticas descriptivas con .describe():")
display(df.describe())

# .shape - Devuelve una tupla que representa las dimensiones del DataFrame (filas, columnas)
print(f"\nDimensiones del DataFrame (filas, columnas): {df.shape}")

# .columns - Devuelve los nombres de las columnas
print(f"\nNombres de las columnas: {df.columns.tolist()}")

# .index - Devuelve el índice del DataFrame
print(f"\nÍndice del DataFrame: {df.index}")

# .dtypes - Devuelve el tipo de datos de cada columna
print("\nTipos de datos de las columnas:")
display(df.dtypes)

DataFrame actual:

    Nombre  Edad      Ciudad
0    Alice    25  Nueva York
1      Bob    30     Londres
2  Charlie    35       París
3    David    40       Tokio

Primeras 2 filas con .head(2):

  Nombre  Edad      Ciudad
0  Alice    25  Nueva York
1    Bob    30     Londres

Última fila con .tail(1):

  Nombre  Edad Ciudad
3  David    40  Tokio

Información del DataFrame con .info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  4 non-null      object
 1   Edad    4 non-null      int64
 2   Ciudad  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Estadísticas descriptivas con .describe():

            Edad
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

Dimensiones del DataFrame (filas, columnas): (4, 3)

Nombres de las columnas: ['Nombre', 'Edad', 'Ciudad']

Índice del DataFrame: RangeIndex(start=0, stop=4, step=1)

Tipos de datos de las columnas:

Nombre    object
Edad       int64
Ciudad    object
dtype: object

## 3. Selección de Datos

La selección de datos es una de las operaciones más fundamentales. Pandas ofrece varias formas de seleccionar filas, columnas o subconjuntos de datos.

### a) Selección de columnas

In [ ]:
# Seleccionar una sola columna (devuelve una Serie)
nombre_col = df['Nombre']
print("\nColumna 'Nombre' (Serie):")
display(nombre_col)
print(f"Tipo de 'nombre_col': {type(nombre_col)}")

# Seleccionar múltiples columnas (devuelve un DataFrame)
columnas_seleccionadas = df[['Nombre', 'Edad']]
print("\nColumnas 'Nombre' y 'Edad' (DataFrame):")
display(columnas_seleccionadas)
print(f"Tipo de 'columnas_seleccionadas': {type(columnas_seleccionadas)}")

### b) Selección de filas por posición (iloc) y por etiqueta (loc)

*   `.iloc`: Se utiliza para la selección basada en la posición entera (similar a los arrays de NumPy).
*   `.loc`: Se utiliza para la selección basada en etiquetas/nombres de índice.

In [ ]:
# .iloc (selección por posición)

# Seleccionar la primera fila
fila_0_iloc = df.iloc[0]
print("\nPrimera fila con .iloc[0]:")
display(fila_0_iloc)

# Seleccionar filas de la 0 a la 2 (exclusivo la 3)
filas_0_a_2_iloc = df.iloc[0:3]
print("\nFilas 0 a 2 con .iloc[0:3]:")
display(filas_0_a_2_iloc)

# Seleccionar filas y columnas específicas por posición
valor_iloc = df.iloc[1, 0] # Fila 1, Columna 0 (Bob)
print(f"\nValor en fila 1, columna 0 con .iloc[1, 0]: {valor_iloc}")

# Seleccionar todas las filas y la primera columna
col_0_iloc = df.iloc[:, 0]
print("\nPrimera columna con .iloc[:, 0]:")
display(col_0_iloc)

# .loc (selección por etiqueta)

# Nota: Por defecto, el índice de un DataFrame es numérico (0, 1, 2, ...).
# Para demostrar .loc con etiquetas personalizadas, primero cambiaremos el índice.
df_con_indice = df.set_index('Nombre')
print("\nDataFrame con 'Nombre' como índice:")
display(df_con_indice)

# Seleccionar una fila por etiqueta de índice
fila_alice_loc = df_con_indice.loc['Alice']
print("\nFila 'Alice' con .loc['Alice']:")
display(fila_alice_loc)

# Seleccionar múltiples filas por etiquetas de índice
filas_multiples_loc = df_con_indice.loc[['Alice', 'Charlie']]
print("\nFilas 'Alice' y 'Charlie' con .loc[['Alice', 'Charlie']]:")
display(filas_multiples_loc)

# Seleccionar filas y columnas específicas por etiqueta
valor_loc = df_con_indice.loc['Bob', 'Edad'] # Fila 'Bob', Columna 'Edad'
print(f"\nValor de la edad de Bob con .loc['Bob', 'Edad']: {valor_loc}")

# Seleccionar todas las filas y columnas específicas por etiqueta
col_ciudad_loc = df_con_indice.loc[:, 'Ciudad']
print("\nColumna 'Ciudad' con .loc[:, 'Ciudad']:")
display(col_ciudad_loc)

### c) Filtrado condicional

Permite seleccionar filas que cumplen una o varias condiciones.

In [ ]:
# Volvemos a usar el DataFrame original sin el índice personalizado
df = df_dict.copy()
print("DataFrame para filtrado:")
display(df)

# Filtrar filas donde la edad es mayor de 30
mayores_de_30 = df[df['Edad'] > 30]
print("\nPersonas con edad > 30:")
display(mayores_de_30)

# Filtrar filas con múltiples condiciones (usando & para 'y', | para 'o')
mayores_de_30_en_ny = df[(df['Edad'] > 30) & (df['Ciudad'] == 'Nueva York')]
print("\nPersonas con edad > 30 Y en Nueva York:")
display(mayores_de_30_en_ny)

# Filtrar filas donde el nombre está en una lista específica
nombres_a_buscar = ['Alice', 'David']
personas_especificas = df[df['Nombre'].isin(nombres_a_buscar)]
print("\nPersonas con nombre 'Alice' o 'David':")
display(personas_especificas)

DataFrame para filtrado:

    Nombre  Edad      Ciudad
0    Alice    25  Nueva York
1      Bob    30     Londres
2  Charlie    35       París
3    David    40       Tokio

Personas con edad > 30:

    Nombre  Edad Ciudad
2  Charlie    35  París
3    David    40  Tokio

Personas con edad > 30 Y en Nueva York:

Empty DataFrame
Columns: [Nombre, Edad, Ciudad]
Index: []

Personas con nombre 'Alice' o 'David':

  Nombre  Edad      Ciudad
0  Alice    25  Nueva York
3  David    40       Tokio

## 4. Modificación de DataFrames

Los DataFrames son mutables, lo que significa que se pueden añadir, modificar o eliminar columnas y filas.

In [ ]:
df = df_dict.copy()
print("DataFrame original:")
display(df)

# Añadir una nueva columna
df['Salario'] = [50000, 60000, 75000, 80000]
print("\nDataFrame después de añadir 'Salario':")
display(df)

# Modificar valores en una columna existente
df['Edad'] = df['Edad'] + 1 # Aumentar la edad en 1
print("\nDataFrame después de modificar 'Edad':")
display(df)

# Modificar un valor específico usando .loc o .iloc
df.loc[0, 'Salario'] = 55000 # Modificar el salario de Alice
print("\nDataFrame después de modificar el salario de Alice:")
display(df)

# Eliminar una columna (usando .drop() o la palabra clave del)
# df = df.drop(columns=['Ciudad']) # Para eliminar la columna 'Ciudad'
# df.drop(columns=['Salario'], inplace=True) # Eliminar 'Salario' y aplicar los cambios directamente
# del df['Salario'] # Otra forma de eliminar una columna

# Vamos a eliminar 'Ciudad' sin usar inplace para mostrar el resultado temporal
df_sin_ciudad = df.drop(columns=['Ciudad'])
print("\nDataFrame después de eliminar 'Ciudad' (temporalmente):")
display(df_sin_ciudad)
print("DataFrame original (sin cambios):")
display(df)

# Añadir una columna calculada
df['Salario Anual'] = df['Salario'] * 12
print("\nDataFrame después de añadir 'Salario Anual':")
display(df)

## 5. Manejo de Valores Faltantes (Missing Values)

Los valores faltantes son comunes en los datos del mundo real y se representan como `NaN` (Not a Number) en Pandas. Es crucial manejarlos adecuadamente.

In [ ]:
# Crear un DataFrame con valores faltantes para demostración
data_na = {
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Precio': [10, np.nan, 15, 20, np.nan],
    'Cantidad': [100, 200, np.nan, 150, 120],
    'Descuento': [0.1, 0.05, 0.2, np.nan, 0.15]
}
df_na = pd.DataFrame(data_na)
print("DataFrame con valores faltantes:")
display(df_na)

# .isnull() - Devuelve un DataFrame booleano indicando dónde hay NaN
print("\n.isnull():")
display(df_na.isnull())

# .notnull() - Opuesto a .isnull()
print("\n.notnull():")
display(df_na.notnull())

# .sum() en .isnull() - Cuenta el número de NaN por columna
print("\nConteo de valores faltantes por columna:")
display(df_na.isnull().sum())

# .dropna() - Elimina filas o columnas con valores faltantes
# Eliminar filas con cualquier valor NaN
df_dropna_rows = df_na.dropna()
print("\nDataFrame después de eliminar filas con NaN:")
display(df_dropna_rows)

# Eliminar columnas con cualquier valor NaN
df_dropna_cols = df_na.dropna(axis=1)
print("\nDataFrame después de eliminar columnas con NaN:")
display(df_dropna_cols)

# .fillna() - Rellena los valores faltantes
# Rellenar con un valor específico (ej. 0)
df_fillna_0 = df_na.fillna(0)
print("\nDataFrame después de rellenar NaN con 0:")
display(df_fillna_0)

# Rellenar con la media de la columna (solo para columnas numéricas)
df_fillna_mean = df_na.copy()
df_fillna_mean['Precio'] = df_fillna_mean['Precio'].fillna(df_fillna_mean['Precio'].mean())
df_fillna_mean['Cantidad'] = df_fillna_mean['Cantidad'].fillna(df_fillna_mean['Cantidad'].mean())
df_fillna_mean['Descuento'] = df_fillna_mean['Descuento'].fillna(df_fillna_mean['Descuento'].mean())
print("\nDataFrame después de rellenar NaN con la media:")
display(df_fillna_mean)

# Rellenar usando el método forward-fill (ffill) o backward-fill (bfill)
# ffill: propaga la última observación válida hacia adelante
df_fillna_ffill = df_na.fillna(method='ffill')
print("\nDataFrame después de rellenar NaN con ffill:")
display(df_fillna_ffill)

## 6. Agrupación de Datos (Group By)

La operación `groupby()` es una herramienta poderosa para dividir los datos en grupos basados en algunas columnas, aplicar una función a cada grupo de forma independiente y luego combinar los resultados.

In [ ]:
import pandas as pd
data_ventas = {
    'Vendedor': ['Ana', 'Juan', 'Ana', 'María', 'Juan', 'Ana', 'María'],
    'Región': ['Este', 'Oeste', 'Este', 'Norte', 'Oeste', 'Este', 'Norte'],
    'Ventas': [100, 150, 120, 200, 180, 90, 250]
}
df_ventas = pd.DataFrame(data_ventas)
print("DataFrame de ventas original:")
display(df_ventas)

# Agrupar por 'Vendedor' y calcular la suma de 'Ventas'
ventas_por_vendedor = df_ventas.groupby('Vendedor')['Ventas'].sum()
print("\nSuma de ventas por vendedor:")
display(ventas_por_vendedor)

# Agrupar por 'Región' y calcular el promedio de 'Ventas'
ventas_promedio_region = df_ventas.groupby('Región')['Ventas'].mean()
print("\nPromedio de ventas por región:")
display(ventas_promedio_region)

# Agrupar por múltiples columnas y aplicar múltiples funciones de agregación
ventas_multi_agg = df_ventas.groupby(['Vendedor', 'Región']).agg(
    Total_Ventas=('Ventas', 'sum'),
    Conteo_Ventas=('Ventas', 'count'),
    Promedio_Ventas=('Ventas', 'mean')
).reset_index()
print("\nAgregación por Vendedor y Región:")
display(ventas_multi_agg)

DataFrame de ventas original:

  Vendedor Región  Ventas
0      Ana   Este     100
1     Juan  Oeste     150
2      Ana   Este     120
3    María  Norte     200
4     Juan  Oeste     180
5      Ana   Este      90
6    María  Norte     250

Suma de ventas por vendedor:

Vendedor
Ana      310
Juan     330
María    450
Name: Ventas, dtype: int64

Promedio de ventas por región:

Región
Este     103.333333
Norte    225.000000
Oeste    165.000000
Name: Ventas, dtype: float64

Agregación por Vendedor y Región:

  Vendedor Región  Total_Ventas  Conteo_Ventas  Promedio_Ventas
0      Ana   Este           310              3       103.333333
1     Juan  Oeste           330              2       165.000000
2    María  Norte           450              2       225.000000

from matplotlib import pyplot as plt
ventas_multi_agg['Total_Ventas'].plot(kind='hist', bins=20, title='Total_Ventas')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ventas_multi_agg['Conteo_Ventas'].plot(kind='hist', bins=20, title='Conteo_Ventas')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ventas_multi_agg['Promedio_Ventas'].plot(kind='hist', bins=20, title='Promedio_Ventas')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
ventas_multi_agg.groupby('Vendedor').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
ventas_multi_agg.groupby('Región').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ventas_multi_agg.plot(kind='scatter', x='Total_Ventas', y='Conteo_Ventas', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ventas_multi_agg.plot(kind='scatter', x='Conteo_Ventas', y='Promedio_Ventas', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Total_Ventas']
  ys = series['Conteo_Ventas']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ventas_multi_agg.sort_values('Total_Ventas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Vendedor')):
  _plot_series(series, series_name, i)
  fig.legend(title='Vendedor', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Total_Ventas')
_ = plt.ylabel('Conteo_Ventas')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Total_Ventas']
  ys = series['Conteo_Ventas']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ventas_multi_agg.sort_values('Total_Ventas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Región')):
  _plot_series(series, series_name, i)
  fig.legend(title='Región', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Total_Ventas')
_ = plt.ylabel('Conteo_Ventas')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Total_Ventas']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Total_Ventas'}, axis=1)
              .sort_values('Total_Ventas', ascending=True))
  xs = counted['Total_Ventas']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ventas_multi_agg.sort_values('Total_Ventas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Vendedor')):
  _plot_series(series, series_name, i)
  fig.legend(title='Vendedor', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Total_Ventas')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Total_Ventas']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Total_Ventas'}, axis=1)
              .sort_values('Total_Ventas', ascending=True))
  xs = counted['Total_Ventas']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ventas_multi_agg.sort_values('Total_Ventas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Región')):
  _plot_series(series, series_name, i)
  fig.legend(title='Región', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Total_Ventas')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
ventas_multi_agg['Total_Ventas'].plot(kind='line', figsize=(8, 4), title='Total_Ventas')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
ventas_multi_agg['Conteo_Ventas'].plot(kind='line', figsize=(8, 4), title='Conteo_Ventas')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
ventas_multi_agg['Promedio_Ventas'].plot(kind='line', figsize=(8, 4), title='Promedio_Ventas')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Región'].value_counts()
    for x_label, grp in ventas_multi_agg.groupby('Vendedor')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Vendedor')
_ = plt.ylabel('Región')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ventas_multi_agg['Vendedor'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ventas_multi_agg, x='Total_Ventas', y='Vendedor', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ventas_multi_agg['Región'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ventas_multi_agg, x='Total_Ventas', y='Región', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ventas_multi_agg['Vendedor'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ventas_multi_agg, x='Conteo_Ventas', y='Vendedor', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ventas_multi_agg['Región'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ventas_multi_agg, x='Conteo_Ventas', y='Región', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

## 7. Combinación de DataFrames (Merge, Join, Concat)

Pandas proporciona herramientas flexibles para combinar DataFrames, similares a las operaciones JOIN en SQL.

### a) `pd.concat()`: Concatena DataFrames a lo largo de un eje (filas o columnas).

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']},
                   index=[0, 1, 2])
df2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'], 'B': ['B3', 'B4', 'B5']},
                   index=[3, 4, 5])

print("df1:")
display(df1)
print("\ndf2:")
display(df2)

# Concatenar por filas (axis=0, por defecto)
df_concat_rows = pd.concat([df1, df2])
print("\nConcatenación por filas:")
display(df_concat_rows)

# Concatenar por columnas (axis=1)
df_concat_cols = pd.concat([df1, df2], axis=1)
print("\nConcatenación por columnas:")
display(df_concat_cols)

df1:

    A   B
0  A0  B0
1  A1  B1
2  A2  B2

df2:

    A   B
3  A3  B3
4  A4  B4
5  A5  B5

Concatenación por filas:

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
5  A5  B5

Concatenación por columnas:

     A    B    A    B
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4
5  NaN  NaN   A5   B5

### b) `pd.merge()`: Combina DataFrames basándose en valores de columnas comunes (claves), similar a las uniones de bases de datos.

In [ ]:
df_empleados = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Nombre': ['Alice', 'Bob', 'Charlie', 'David'],
    'DepartamentoID': [101, 102, 101, 103]
})

df_departamentos = pd.DataFrame({
    'DepartamentoID': [101, 102, 103, 104],
    'Departamento': ['Marketing', 'Ventas', 'IT', 'RRHH']
})

print("df_empleados:")
display(df_empleados)
print("\ndf_departamentos:")
display(df_departamentos)

# Merge interno (por defecto): solo mantiene las filas donde las claves coinciden en ambos DataFrames
df_merged_inner = pd.merge(df_empleados, df_departamentos, on='DepartamentoID', how='inner')
print("\nMerge interno (inner join):")
display(df_merged_inner)

# Merge izquierdo (left join): mantiene todas las filas del DataFrame izquierdo y coincide con el derecho
df_merged_left = pd.merge(df_empleados, df_departamentos, on='DepartamentoID', how='left')
print("\nMerge izquierdo (left join):")
display(df_merged_left)

# Merge derecho (right join): mantiene todas las filas del DataFrame derecho y coincide con el izquierdo
df_merged_right = pd.merge(df_empleados, df_departamentos, on='DepartamentoID', how='right')
print("\nMerge derecho (right join):")
display(df_merged_right)

# Merge externo (outer join): mantiene todas las filas de ambos DataFrames, rellenando con NaN donde no hay coincidencia
df_merged_outer = pd.merge(df_empleados, df_departamentos, on='DepartamentoID', how='outer')
print("\nMerge externo (outer join):")
display(df_merged_outer)

## Conclusión

Este notebook cubre los fundamentos de los DataFrames de Pandas, incluyendo su creación, exploración básica, selección de datos, modificación, manejo de valores faltantes y combinación. Estas son las operaciones más comunes y esenciales para trabajar con datos tabulares en Python usando Pandas. ¡Con estos conocimientos, estás bien equipado para empezar a manipular y analizar tus propios conjuntos de datos!