# Introducción a Pandas Series

Una `Serie` de Pandas es una estructura de datos unidimensional capaz de contener cualquier tipo de datos (enteros, cadenas, números de punto flotante, objetos de Python, etc.). Es muy similar a una columna en una tabla de hoja de cálculo o una base de datos, o un array de NumPy de una dimensión. La diferencia principal es que una Serie tiene un *índice* asociado a los datos, lo que permite un acceso y manipulación más flexibles.

Comencemos importando la librería `pandas`.

In [ ]:
import pandas as pd
import numpy as np

print("Pandas y NumPy importados correctamente.")

Pandas y NumPy importados correctamente.

## Creación de Series

Se pueden crear Series de varias maneras:

### 1. Desde una lista de Python

In [ ]:
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
display(s)
print(type(s))

Por defecto, Pandas asigna un índice numérico que comienza en 0.

### 2. Desde un array de NumPy

In [ ]:
arr = np.array([100, 200, 300, 400])
s_np = pd.Series(arr)
display(s_np)

### 3. Desde un diccionario de Python

Las claves del diccionario se convertirán en el índice de la Serie y los valores en los datos.

In [ ]:
data_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
s_dict = pd.Series(data_dict)
display(s_dict)

### 4. Con un índice personalizado

Podemos especificar un índice explícitamente al crear la Serie.

In [ ]:
data = [10, 20, 30, 40]
index = ['uno', 'dos', 'tres', 'cuatro']
s_custom_index = pd.Series(data, index=index)
display(s_custom_index)

## Acceso a elementos de una Serie

Los elementos de una Serie se pueden acceder de varias maneras, similar a los arrays de NumPy o los diccionarios de Python.

### 1. Por etiqueta de índice

In [ ]:
display(s_custom_index['uno'])

# Acceso a múltiples elementos por una lista de etiquetas
display(s_custom_index[['uno', 'tres']])

### 2. Por posición entera (iloc)

Podemos usar `iloc` para acceder a elementos por su posición numérica, como en una lista o array.

In [ ]:
display(s_custom_index.iloc[0]) # Primer elemento
display(s_custom_index.iloc[2]) # Tercer elemento

# Acceso a múltiples elementos por una lista de posiciones
display(s_custom_index.iloc[[0, 3]])

### 3. Slicing

El slicing funciona de forma similar a las listas y arrays, tanto por etiquetas como por posiciones.

In [ ]:
# Slicing por posición
display(s_custom_index[0:2]) # Elementos en posición 0 y 1

# Slicing por etiqueta (¡el final es inclusivo!)
display(s_custom_index['uno':'tres']) # Elementos desde 'uno' hasta 'tres' inclusive

## Atributos comunes de una Serie

Las Series tienen varios atributos útiles para inspeccionar sus características.

In [ ]:
s_example = pd.Series([10, 20, 30, 'cuarenta', 50.5], name='MiSerieEjemplo', index=['a', 'b', 'c', 'd', 'e'])
display(s_example)

print(f"Índice: {s_example.index.tolist()}")
print(f"Valores: {s_example.values}")
print(f"Tipo de dato (dtype): {s_example.dtype}")
print(f"Nombre de la Serie: {s_example.name}")
print(f"Número de elementos (size): {s_example.size}")
print(f"Forma (shape): {s_example.shape}") # Siempre es (n,) para una Serie

## Operaciones Básicas con Series

Las Series de Pandas permiten realizar operaciones matemáticas de forma vectorizada, similar a NumPy, y manejan automáticamente los índices.

### 1. Operaciones Aritméticas

In [ ]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

print("s1:"); display(s1)
print("s2:"); display(s2)

print("\nSuma (s1 + s2):"); display(s1 + s2)
print("Resta (s1 - s2):"); display(s1 - s2)
print("Multiplicación (s1 * s2):"); display(s1 * s2)
print("División (s1 / s2):"); display(s1 / s2)

# Las operaciones se alinean por índice. Si los índices no coinciden, se producirá NaN.
s3 = pd.Series([5, 6, 7], index=['b', 'c', 'e'])
print("\nSuma (s1 + s3) con índices no coincidentes:"); display(s1 + s3)

s1:

a    1
b    2
c    3
d    4
dtype: int64

s2:

a    10
b    20
c    30
d    40
dtype: int64

Suma (s1 + s2):

a    11
b    22
c    33
d    44
dtype: int64

Resta (s1 - s2):

a    -9
b   -18
c   -27
d   -36
dtype: int64

Multiplicación (s1 * s2):

a     10
b     40
c     90
d    160
dtype: int64

División (s1 / s2):

a    0.1
b    0.1
c    0.1
d    0.1
dtype: float64

Suma (s1 + s3) con índices no coincidentes:

a    NaN
b    7.0
c    9.0
d    NaN
e    NaN
dtype: float64

### 2. Indexación Booleana

Permite seleccionar elementos basándose en una condición lógica.

In [ ]:
s_numeric = pd.Series([10, 15, 20, 25, 30], index=['a', 'b', 'c', 'd', 'e'])
display(s_numeric)

# Seleccionar elementos mayores que 20
mask = s_numeric > 20
print("\nMáscara booleana:"); display(mask)
print("Elementos mayores que 20:"); display(s_numeric[mask])

# O de forma abreviada
print("\nElementos mayores que 20 (abreviado):"); display(s_numeric[s_numeric > 20])

### 3. Manejo de Valores Faltantes (NaN)

Las Series pueden contener valores `NaN` (Not a Number) para representar datos faltantes. Pandas proporciona métodos para identificarlos y manejarlos.

In [ ]:
s_nan = pd.Series([1, 2, np.nan, 4, np.nan, 6])
display(s_nan)

print("\n¿Valores nulos? (isnull):"); display(s_nan.isnull())
print("¿Valores no nulos? (notnull):"); display(s_nan.notnull())

print("\nEliminar valores nulos (dropna):"); display(s_nan.dropna())

print("\nRellenar valores nulos con 0 (fillna):"); display(s_nan.fillna(0))
print("\nRellenar valores nulos con el valor anterior (fillna method='ffill'):"); display(s_nan.fillna(method='ffill'))
print("\nRellenar valores nulos con el valor siguiente (fillna method='bfill'):"); display(s_nan.fillna(method='bfill'))

### 4. Estadísticas Descriptivas

Se pueden obtener rápidamente estadísticas resumidas de una Serie numérica.

In [ ]:
s_stats = pd.Series([10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 60, 70])
display(s_stats)

print(f"Media: {s_stats.mean()}")
print(f"Mediana: {s_stats.median()}")
print(f"Desviación estándar: {s_stats.std()}")
print(f"Mínimo: {s_stats.min()}")
print(f"Máximo: {s_stats.max()}")

print("\nEstadísticas descriptivas completas (describe()):")
display(s_stats.describe())

0     10
1     20
2     30
3     40
4     50
5     10
6     20
7     30
8     40
9     50
10    60
11    70
dtype: int64

Media: 35.833333333333336
Mediana: 35.0
Desviación estándar: 19.28651593652148
Mínimo: 10
Máximo: 70

Estadísticas descriptivas completas (describe()):

count    12.000000
mean     35.833333
std      19.286516
min      10.000000
25%      20.000000
50%      35.000000
75%      50.000000
max      70.000000
dtype: float64

Con esto, tienes una buena base para empezar a trabajar con Series de Pandas. Las Series son el bloque fundamental de los DataFrames, que exploraremos en otro momento.